name: Executar Robo de Analises Diarias

on:
  schedule:
    - cron: '0 10 * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  executar-robo:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    - run: pip install -r requirements.txt
    - env:
        GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
        FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
      run: python main.py
    - run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "github-actions[bot]@users.noreply.github.com"
        git add dados_jogos_hoje.json
        git commit -m "Auto: Analises atualizadas com API de Futebol" || exit 0
        git push
